import { defineConfig } from "astro/config";

const isGitHubPages = process.env.GITHUB_PAGES === "true";
const site = isGitHubPages
  ? "https://vilo0411.github.io"
  : "https://valueinvesting.com.vn";
const base = isGitHubPages ? "/investing" : "/";
const basePrefix = base === "/" ? "" : base;

// Rewrite absolute internal links in markdown bodies (e.g. /dau-tu/...) to
// include the configured `base`. Astro does NOT prefix base onto raw links
// written inside markdown content, so on GitHub Pages (base=/investing) those
// links would 404. No-op in dev where base="/".
function rehypeBaseLinks() {
  return (tree) => {
    if (base === "/") return;
    const walk = (node) => {
      if (
        node.type === "element" &&
        node.tagName === "a" &&
        node.properties &&
        typeof node.properties.href === "string"
      ) {
        const href = node.properties.href;
        if (
          href.startsWith("/") &&
          !href.startsWith("//") &&
          href !== base &&
          !href.startsWith(`${base}/`)
        ) {
          node.properties.href = href === "/" ? `${base}/` : `${base}${href}`;
        }
      }
      if (node.children) node.children.forEach(walk);
    };
    walk(tree);
  };
}

export default defineConfig({
  site,
  base,
  markdown: {
    rehypePlugins: [rehypeBaseLinks],
  },
  // Sitemaps are generated by custom endpoints (src/pages/sitemap*.xml.ts):
  // a sitemap.xml index pointing to per-section child sitemaps.
  integrations: [],
  // Redirect targets are absolute from the domain root, so they must carry the
  // `base` prefix themselves (Astro does not add it). Empty prefix in dev (base="/").
  redirects: {
    "/co-phieu/": `${basePrefix}/dau-tu/co-phieu/`,
    "/etf/": `${basePrefix}/dau-tu/etf/`,
    "/quy-dau-tu/": `${basePrefix}/dau-tu/etf/`,
    "/dau-tu/quy-dau-tu/": `${basePrefix}/dau-tu/etf/`,
    "/trai-phieu/": `${basePrefix}/dau-tu/trai-phieu/`,
    "/phai-sinh/": `${basePrefix}/dau-tu/phai-sinh/`,
  },
});
