import { defineConfig } from "astro/config";

const isGitHubPages = process.env.GITHUB_PAGES === "true";
const site = isGitHubPages
  ? "https://vilo0411.github.io"
  : "https://valueinvesting.com.vn";
const base = isGitHubPages ? "/investing" : "/";
const basePrefix = base === "/" ? "" : base;

// Rewrite absolute internal links in markdown bodies (e.g. /dau-tu/...) to
// include the configured `base`. Astro does NOT prefix base onto raw links
// written inside markdown content, so on GitHub Pages (base=/investing) those
// links would 404. No-op in dev where base="/".
function rehypeBaseLinks() {
  return (tree) => {
    if (base === "/") return;
    const walk = (node) => {
      if (
        node.type === "element" &&
        node.tagName === "a" &&
        node.properties &&
        typeof node.properties.href === "string"
      ) {
        const href = node.properties.href;
        if (
          href.startsWith("/") &&
          !href.startsWith("//") &&
          href !== base &&
          !href.startsWith(`${base}/`)
        ) {
          node.properties.href = href === "/" ? `${base}/` : `${base}${href}`;
        }
      }
      if (node.children) node.children.forEach(walk);
    };
    walk(tree);
  };
}

// Wrap standalone block images in <figure>, with a visible <figcaption>.
// Two markdown shapes are recognised inside a single paragraph:
//   ![alt](src)              -> figure + figcaption taken from the alt text
//   ![alt](src)\n*caption*   -> figure + figcaption taken from the italic line
//                               (img keeps its alt for SEO / screen readers)
// Paragraphs mixing an image with other inline text are left untouched.
function rehypeFigure() {
  const isBlank = (node) => node.type === "text" && /^\s*$/.test(node.value);
  const isEl = (node, tag) => node?.type === "element" && node.tagName === tag;

  return (tree) => {
    const walk = (node) => {
      if (!node.children) return;
      node.children = node.children.map((child) => {
        if (isEl(child, "p")) {
          const meaningful = child.children.filter((c) => !isBlank(c));
          const img = meaningful[0];

          // Case A: image alone -> caption from alt text.
          if (meaningful.length === 1 && isEl(img, "img")) {
            const alt =
              typeof img.properties?.alt === "string" ? img.properties.alt : "";
            return makeFigure(img, alt.trim() ? [{ type: "text", value: alt }] : null);
          }

          // Case B: image immediately followed by an italic caption line.
          if (
            meaningful.length === 2 &&
            isEl(img, "img") &&
            isEl(meaningful[1], "em")
          ) {
            return makeFigure(img, meaningful[1].children);
          }
        }
        walk(child);
        return child;
      });
    };
    walk(tree);
  };

  function makeFigure(img, captionChildren) {
    const children = [img];
    if (captionChildren && captionChildren.length) {
      children.push({
        type: "element",
        tagName: "figcaption",
        properties: {},
        children: captionChildren,
      });
    }
    return {
      type: "element",
      tagName: "figure",
      properties: { className: ["article-figure"] },
      children,
    };
  }
}

export default defineConfig({
  site,
  base,
  markdown: {
    rehypePlugins: [rehypeBaseLinks, rehypeFigure],
  },
  // Sitemaps are generated by custom endpoints (src/pages/sitemap*.xml.ts):
  // a sitemap.xml index pointing to per-section child sitemaps.
  integrations: [],
  // Redirect targets are absolute from the domain root, so they must carry the
  // `base` prefix themselves (Astro does not add it). Empty prefix in dev (base="/").
  redirects: {
    "/co-phieu/": `${basePrefix}/dau-tu/co-phieu/`,
    "/etf/": `${basePrefix}/dau-tu/etf/`,
    "/quy-dau-tu/": `${basePrefix}/dau-tu/etf/`,
    "/dau-tu/quy-dau-tu/": `${basePrefix}/dau-tu/etf/`,
    "/trai-phieu/": `${basePrefix}/dau-tu/trai-phieu/`,
    "/phai-sinh/": `${basePrefix}/dau-tu/phai-sinh/`,
  },
});
